# Generated by Django 3.1.5 on 2021-10-13 13:27

from django.db import migrations, models
import django.db.models.deletion
import scholarships.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='CrowdSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('amount', models.CharField(blank=True, max_length=300, null=True)),
                ('eligibility', models.TextField(blank=True, max_length=1000, null=True)),
                ('contact', models.CharField(blank=True, max_length=300, null=True)),
                ('desc', models.TextField(blank=True, max_length=3000, null=True)),
                ('person_name', models.CharField(blank=True, max_length=300, null=True)),
                ('person_email', models.CharField(blank=True, max_length=300, null=True)),
                ('person_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('reviewed', models.BooleanField(blank=True, default=False, null=True)),
                ('sub_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'CrowdSource',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Religion',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Type',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.country')),
            ],
            options={
                'verbose_name_plural': 'State',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('about', models.TextField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=scholarships.models.upload_location)),
                ('eligibility', models.TextField(blank=True, max_length=50000, null=True)),
                ('content', models.TextField(blank=True, max_length=50000, null=True)),
                ('award', models.CharField(max_length=150)),
                ('updated_on', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('site_url', models.CharField(blank=True, max_length=300, null=True)),
                ('deadline', models.DateField()),
                ('contact', models.CharField(blank=True, max_length=150, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.category')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.country')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.course')),
                ('gender', models.ManyToManyField(to='scholarships.Gender')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.religion')),
                ('sclass', models.ManyToManyField(to='scholarships.Class')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.state')),
                ('stype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scholarships.type')),
            ],
            options={
                'verbose_name_plural': 'Scholarship',
            },
        ),
    ]
